apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: passagens-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-passagens:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_DB
              value: "venda_passagens"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
