apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  namespace: passagens-app
spec:
  type: NodePort
  selector:
    app: fastapi
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30080
