version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_passagens
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: .
    container_name: fastapi_backend
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_web
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"  
      PGADMIN_DEFAULT_PASSWORD: "admin"         
    ports:
      - "5050:80"
    networks:
      - app-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data:

networks:
  app-network:
    driver: bridge