apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: passagens-app
spec:
  type: NodePort
  selector:
    app: pgadmin
  ports:
    - port: 5050
      targetPort: 80
      nodePort: 30550
